### ISSUE TITLE
Bug: comment on the new line after the single expression within the begin..end block

### ISSUE THREAD

**Issue by zindel** [ocaml-ppx/ocamlformat#2508] opened 2024-01-12 12:17 UTC
**Describe the bug**
```
$ cat x.ml && ocamlformat x.ml
if true then begin
  print_endline "Hello, world!"
  (* some comment here *)
end
ocamlformat: Cannot process "x.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: generating invalid ocaml syntax.
``` 

**How to Reproduce**
See above.
```
$ ocamlformat --version
0.24.1
$ ocamlformat --print-config
profile=default (file ../.ocamlformat:2)
range=<whole input> (profile default (file ../.ocamlformat:2))
quiet=false (profile default (file ../.ocamlformat:2))
ocaml-version=4.14.0 (file ../.ocamlformat:3)
max-iters=10 (profile default (file ../.ocamlformat:2))
margin-check=false (profile default (file ../.ocamlformat:2))
disable=false (profile default (file ../.ocamlformat:2))
debug=false (profile default (file ../.ocamlformat:2))
comment-check=true (profile default (file ../.ocamlformat:2))
wrap-fun-args=true (profile default (file ../.ocamlformat:2))
wrap-comments=false (profile default (file ../.ocamlformat:2))
type-decl-indent=2 (profile default (file ../.ocamlformat:2))
type-decl=sparse (file ../.ocamlformat:19)
stritem-extension-indent=0 (profile default (file ../.ocamlformat:2))
space-around-variants=true (profile default (file ../.ocamlformat:2))
space-around-records=true (profile default (file ../.ocamlformat:2))
space-around-lists=true (profile default (file ../.ocamlformat:2))
space-around-arrays=true (profile default (file ../.ocamlformat:2))
single-case=compact (profile default (file ../.ocamlformat:2))
sequence-style=terminator (profile default (file ../.ocamlformat:2))
sequence-blank-line=preserve-one (profile default (file ../.ocamlformat:2))
parse-toplevel-phrases=false (profile default (file ../.ocamlformat:2))
parse-docstrings=false (profile default (file ../.ocamlformat:2))
parens-tuple-patterns=multi-line-only (profile default (file ../.ocamlformat:2))
parens-tuple=multi-line-only (file ../.ocamlformat:18)
parens-ite=true (file ../.ocamlformat:17)
ocp-indent-compat=false (profile default (file ../.ocamlformat:2))
nested-match=align (file ../.ocamlformat:16)
module-item-spacing=preserve (file ../.ocamlformat:15)
max-indent=2 (file ../.ocamlformat:14)
match-indent-nested=never (profile default (file ../.ocamlformat:2))
match-indent=0 (profile default (file ../.ocamlformat:2))
margin=120 (file ../.ocamlformat:13)
line-endings=lf (profile default (file ../.ocamlformat:2))
let-module=compact (profile default (file ../.ocamlformat:2))
let-binding-spacing=compact (profile default (file ../.ocamlformat:2))
let-binding-indent=2 (profile default (file ../.ocamlformat:2))
let-and=sparse (file ../.ocamlformat:12)
leading-nested-match-parens=true (file ../.ocamlformat:11)
infix-precedence=indent (profile default (file ../.ocamlformat:2))
indicate-nested-or-patterns=unsafe-no (profile default (file ../.ocamlformat:2))
indicate-multiline-delimiters=no (profile default (file ../.ocamlformat:2))
indent-after-in=0 (profile default (file ../.ocamlformat:2))
if-then-else=compact (profile default (file ../.ocamlformat:2))
function-indent-nested=never (profile default (file ../.ocamlformat:2))
function-indent=2 (profile default (file ../.ocamlformat:2))
field-space=loose (profile default (file ../.ocamlformat:2))
extension-indent=2 (profile default (file ../.ocamlformat:2))
exp-grouping=preserve (file ../.ocamlformat:10)
dock-collection-brackets=true (profile default (file ../.ocamlformat:2))
doc-comments-tag-only=default (profile default (file ../.ocamlformat:2))
doc-comments-padding=2 (profile default (file ../.ocamlformat:2))
doc-comments=before (file ../.ocamlformat:9)
disambiguate-non-breaking-match=false (profile default (file ../.ocamlformat:2))
cases-matching-exp-indent=normal (profile default (file ../.ocamlformat:2))
cases-exp-indent=2 (file ../.ocamlformat:8)
break-struct=force (profile default (file ../.ocamlformat:2))
break-string-literals=auto (profile default (file ../.ocamlformat:2))
break-sequences=true (profile default (file ../.ocamlformat:2))
break-separators=after (profile default (file ../.ocamlformat:2))
break-infix-before-func=false (file ../.ocamlformat:6) -- Warning (redundant):  (profile default (file ../.ocamlformat:2))
break-infix=fit-or-vertical (file ../.ocamlformat:7)
break-fun-sig=wrap (profile default (file ../.ocamlformat:2))
break-fun-decl=wrap (profile default (file ../.ocamlformat:2))
break-collection-expressions=fit-or-vertical (profile default (file ../.ocamlformat:2))
break-cases=toplevel (file ../.ocamlformat:5)
break-before-in=fit-or-vertical (profile default (file ../.ocamlformat:2))
assignment-operator=end-line (profile default (file ../.ocamlformat:2))
```
(Side note: I realized that `--print-config` doesn't print the own version of the `ocamlformat`. It'd be nice if it is included though)

**Comment by Julow** [comment] 2024-02-05 16:14
Thanks for the report. It would be nice indeed to include the user's configuration in the output of `--print-config`. It is possible to recover it but it is some work.

Your configuration looks like this:
```
# This is not the intended use of OCamlformat
profile=default
ocaml-version=4.14.0
break-cases=toplevel
break-infix-before-func=false
cases-exp-indent=2
doc-comments=before
exp-grouping=preserve
leading-nested-match-parens=true
let-and=sparse
margin=120
max-indent=2
module-item-spacing=preserve
nested-match=align
parens-ite=true
parens-tuple=multi-line-only
```

The bug is caused by the `exp-grouping=preserve` option and it seems fixed on the main branch.

**Closed by Julow** 2024-02-05 16:14 UTC
Labels: Kind/Bug :x:
