### ISSUE TITLE
Bug: ocamlformat "cannot process" when module type preceded by comment

### ISSUE THREAD

**Issue by tomjridge** [ocaml-ppx/ocamlformat#1982] opened 2022-01-18 16:39 UTC
For the file:

```
[@@@ocamlformat "disable=true"]

(** Comment 1 *)

(** Comment 2 this comment causes problems *)
module type S = sig

end
```

I currently get the following: 

```
ocamlformat: Cannot process "tmp.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: doc comments changed.
File "_none_", line 0, characters -1--1::
Error: Docstring (**  Comment 2 this comment causes problems  *) dropped.
```

If I remove comment 2, things are fine.

**Comment by gpetiot** [comment] 2022-01-21 10:39
This is a duplicate of #1545, I didn't make any progress on how to fix this unfortunately.

In the meantime maybe using a `.ocamlformat-ignore` file instead of the `[@@@ocamlformat "disable"]` attribute might be able to achieve what you want.

**Comment by gpetiot** [comment] 2022-02-21 16:28
Closing since this is a duplicate.

**Closed by gpetiot** 2022-02-21 16:28 UTC
Labels: Kind/Bug :x:
