### ISSUE TITLE
Bug: Regression: Missing break after struct...end

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1144] opened 2019-11-13 10:58 UTC
**Describe the bug**
Constructs of the form `struct ... end : mty` where `mty` does not fit on a single line no longer have a break before `: mty`.

**How to Reproduce**
On master (8943c45):
```
$ cat test/failing/struct_sig.ml
let hashed_obj eq =
  ( module struct
    type t = Hashing.hash_value * Obj.t

    let hash ((h, _) : t) = (h :> int)

    let equal ((h1, o1) : t) ((h2, o2) : t) =
      Int.equal (h1 :> int) (h2 :> int) && eq o1 o2
  end
  : Caml.Hashtbl.HashedType
    with type t = Hashing.hash_value * Obj.t )
$ _build/default/src/ocamlformat.exe test/failing/struct_sig.ml
let hashed_obj eq =
  ( module struct
    type t = Hashing.hash_value * Obj.t

    let hash ((h, _) : t) = (h :> int)

    let equal ((h1, o1) : t) ((h2, o2) : t) =
      Int.equal (h1 :> int) (h2 :> int) && eq o1 o2
  end : Caml.Hashtbl.HashedType
    with type t = Hashing.hash_value * Obj.t )
```
Note the missing break after `end` on the second-to-last line.

**Comment by Julow** [comment] 2019-12-10 15:35
This has been changed on purpose in https://github.com/ocaml-ppx/ocamlformat/pull/739 (in OCamlformat 0.10).

There was two reasons:
- When the module type is "simple", the break seems unecessary
  ```
  (module struct
    ...
  end : S )
  ```
- Very often, there is a break between the module type and "with"-constraints
  ```
  (module struct
    ...
  end : S
    with type t = very_long_line )
  ```

I personally prefer that formatting, `end` will always be short and in most case, the module type name is short and the with-constraints are huge.
Why do you consider this a regression ?

**Comment by gpetiot** [comment] 2020-01-20 13:54
How about:
- we wrap the type when it is just an identifier without constraints:
```ocaml
let m =
   (module struct
     let x = 3
   end : S)
```

- and we break before the `:` when there are `with type` constraints:
```ocaml
let m =
  ( module SSMap
  : MapT
     with type key = string
      and type data = string
      and type map = SSMap.map )
```

would that be consistent for you @jberdine @Julow ?

**Comment by Julow** [comment] 2020-03-23 11:50
@gpetiot That was the formatting before https://github.com/ocaml-ppx/ocamlformat/pull/739.
The reasoning was that breaking the `: S` part most of the time makes short lines and that the syntax cannot be complicated.

**Comment by Julow** [comment] 2020-03-23 11:51
Note that this is only for module packs. I'm closing this issue for now, feel free to reopen if needed !

**Closed by Julow** 2020-03-23 11:51 UTC
Labels: Kind/Bug :x:
