### ISSUE TITLE
Mantaining subsequent newlines

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#807] opened 2019-04-27 21:32 UTC
`ocamlformat` tends to pretty aggressively remove ‘extra newlines’ that are really important for readability. I'd love to see this improved in a variety of situations (basically, this is continuously the behaviour of `ocamlformat` that I find the most frustrating, and that I have many memories of going “well, I guess I'll commit it looking like this, because I don't want to remove `ocamlformat` entirely, but … yuck.)

Take a look at [this series of tests](https://github.com/ELLIOTTCABLE/excmd.js/blob/master/test/parser_test.ml#L20-L96), for instance. `ocamlformat` refuses to allow me to add spacing between any of those, including the ‘major sections.’

One concrete suggestion that would really help: follow `elm-format`'s behaviour, and recognize some form of “header comments.” When seeing those, allow/retain several newlines of extra space on either side:

```ocaml
   test_statement
      "Single command, single explicitly-parameterized flag with a URL payload, followed \
       by a positional parameter"
      "test --foo=google.com/search baz" ;
   test_statement "Single command with mixed flags and parameters"
      "test --foo bar --baz=widget qux -qu ux" ;



   (* ### This is a header *)


   test_script "Statements separated by semicolons" "test; 2test; 3test" ;
   test_script "Statements separated by semicolons, with a trailing semicolon"
      "test; 2test; 3test;" ;
   test_script "Statements, with arguments, separated by semicolons"
      "test --foo bar; 2test --foo=bar; 3test --foo bar" ;
```

Specifically, I'm told that `elm-format` adds three newlines before, and two after, header-comments. (In fact, people were raving about this at Elm In The Spring yesterday — the negative space apparently really aids scan-ability; which is something I really miss being able to do since I've started using an autoformatter.)

In the larger case, I think I'd generally prefer if `ocamlformat` retained the presence/absence of whitespace between comments, or between comments and code. I think that usually, any such negative-space is very intentional:

```ml
   test_statement
      "Single command, single explicitly-parameterized flag with a URL payload, followed \
       by a positional parameter"
      "test --foo=google.com/search baz" ;
   test_statement "Single command with mixed flags and parameters"
      "test --foo bar --baz=widget qux -qu ux" ;

   (* This is a normal comment, but it causes the above newline to be retained *)
   test_script "Statements separated by semicolons" "test; 2test; 3test" ;
   test_script "Statements separated by semicolons, with a trailing semicolon"
      "test; 2test; 3test;" ;
   test_script "Statements, with arguments, separated by semicolons"
      "test --foo bar; 2test --foo=bar; 3test --foo bar" ;
```

**Comment by jberdine** [comment] 2019-04-27 21:46
While noting the original point about empty lines, have you tried multi-line banner comments to achieve something closer to what you want than what ocamlformat does currently? Something such as:
```
test_statement "..." ;
(*
 *
 *
 * header
 *
 *)
test_script ...
```

**Comment by ELLIOTTCABLE** [comment] 2019-04-30 19:32
I have not! And in this case, there's much better refactoring options that help out with the problem (separating into multiple functions, for instance.)

Nonetheless, this seems like a functionality that could be used to great effect in terms of readability. I don't have other examples handy, but I *do* run into this often — I'd say I have ocamlformat compress some readability-negative-space out of a file about every other time I work in OCaml sources, or so!

(I can try and remember to come back and report additional test-cases!)

**Comment by gpetiot** [comment] 2019-05-02 07:29
Duplicate of #554

**Closed by gpetiot** 2019-05-02 07:29 UTC
