### ISSUE TITLE
Bug: expressions with multi-line comments sometimes left as "one line"

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1100] opened 2019-10-25 16:57 UTC
**Describe the bug**
If I write code with a multi-line comment like this, I'd expect `ocamlformat` to leave it split across lines.
```
let _ =
  [ "x"
  ; "y"
  (* first line
     second line *)
  ; "z"
  ]
;;
```
Instead, `ocamlformat` produces this formatting:
```
let _ = [ "x"; "y" (* first line
     second line *); "z" ]
```

**How to Reproduce**
Run with `ocamlformat` built from 953c48a4f63be421f995fb5d4c4168dccd3d4fea and `--profile=janestreet`.

**Comment by gpetiot** [comment] 2019-10-28 17:31
Duplicate of #912

**Closed by gpetiot** 2019-10-28 17:31 UTC
Labels: JaneStreet, Kind/Bug :x:
