### ISSUE TITLE
incoherent formatting for records

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#926] opened 2019-07-16 03:57 UTC
With ocamlformat 0.10, it seems that the records are not formatted the same way when they are pattern matched on or when they are created. Here are two examples. When pattern matching the first field is on the same line than `{`. When creating a new record, the first field is on a different line.

```ocaml
let f () =
  let { aaaaaaaa;
    bbbbbbbbbb;
      ccccccccc;
        dddddddddd;
        eeeeeeeee;
        ffffffffff;
        gggggggggg;
        hhhhhhhhhh;
        iiiiiiiiii;
        jjjjjjjjjjj
      }
    =
    some_value
  in
  {
    aaaaaaaa;
    bbbbbbbbbb;
    ccccccccc;
    dddddddddd;
    eeeeeeeee;
    ffffffffff;
    gggggggggg;
    hhhhhhhhhh;
    iiiiiiiiii;
    jjjjjjjjjjj;
  }

let g () =
  match some_value with
  | { aaaaaaaa;
    bbbbbbbbbb;
      ccccccccc;
      dddddddddd;
      eeeeeeeee;
      ffffffffff;
      gggggggggg;
      hhhhhhhhhh;
      iiiiiiiiii;
      jjjjjjjjjjj
    } ->
    {
      aaaaaaaa;
      bbbbbbbbbb;
      ccccccccc;
      dddddddddd;
      eeeeeeeee;
      ffffffffff;
      gggggggggg;
      hhhhhhhhhh;
      iiiiiiiiii;
      jjjjjjjjjjj;
    }
```

```
break-cases=toplevel
break-infix-before-func=false
break-infix=fit-or-vertical
break-separators=after-and-docked
break-sequences=true
break-struct=natural
cases-exp-indent=2
doc-comments=before
exp-grouping=preserve
field-space=loose
indicate-multiline-delimiters=closing-on-separate-line
indicate-nested-or-patterns=unsafe-no
leading-nested-match-parens=true
let-and=sparse
m=120
max-indent=2
nested-match=align
ocp-indent-compat=true
parens-ite=true
parens-tuple=multi-line-only
sequence-blank-line=preserve-one
sequence-style=terminator
space-around-arrays=true
space-around-lists=true
space-around-records=true
space-around-variants=true
type-decl=sparse
wrap-fun-args=true
```

**Comment by gpetiot** [comment] 2019-07-16 05:00
It looks like a duplicate of #835 to me, can you confirm?

**Comment by Khady** [comment] 2019-07-16 05:20
Hmm I don't know if it's an exact duplicate. As I'm not necessarily asking for the opening bracket to be on a different line (and now there are a lot of moving parts so I'm not exactly sure what is supposed to be the good behavior for every option). It's just a bit surprising that both cases are not handled the same way.

Also, `after-and-docked` doesn't seem to be allowed in `break-cases` unless I missed something.

**Closed** 2019-07-19 10:15 UTC
Labels: Status/1-Acknowledged
