### ISSUE TITLE
Bug: wrap-comments stopped working in 0.26

### ISSUE THREAD

**Issue by vphantom** [ocaml-ppx/ocamlformat#2414] opened 2023-08-01 13:41 UTC
**Describe the bug**

Given `margin = 80`, `parse-docstrings = true` and `wrap-comments = true` my doc-comments used to wrap, but now they don't.  They are affected by `ocamlformat`, for example multiple empty lines are merged into a single one and the ending `*)` is annoyingly merged into the last line of text, but paragraphs are not wrapped.  If I break lines arbitrarily, they stay that way; if I have just one 150-character line, it stays that way too.

**How to Reproduce**

Example:

```ocaml
(** Reading from bytes sequentially.

    These modules were created
    because of the limitations
    of the Stdlib's [Buffer].  There is no performance penalty to using this module.

    These modules were created because of the limitations of the Stdlib's [Buffer].  There is no performance penalty to using this module.

    x *)
```

(Note: that `x` is just my trick to keep `*)` out of the way.)  To be safe, here's `--print`:

```
comment-check=true
debug=false
disable=false
margin-check=false
max-iters=10
ocaml-version=4.04.0
quiet=false
disable-conf-attrs=false
version-check=true
assignment-operator=begin-line (profile janestreet (file .ocamlformat:2))
break-before-in=fit-or-vertical (profile janestreet (file .ocamlformat:2))
break-cases=fit-or-vertical (profile janestreet (file .ocamlformat:2))
break-collection-expressions=fit-or-vertical (profile janestreet (file .ocamlformat:2))
break-colon=after (file .ocamlformat:6)
break-fun-decl=wrap (file .ocamlformat:7)
break-fun-sig=fit-or-vertical (profile janestreet (file .ocamlformat:2))
break-infix=fit-or-vertical (profile janestreet (file .ocamlformat:2))
break-infix-before-func=false (file .ocamlformat:8)
break-separators=after (file .ocamlformat:9)
break-sequences=false (file .ocamlformat:10)
break-string-literals=auto (profile janestreet (file .ocamlformat:2))
break-struct=force (profile janestreet (file .ocamlformat:2))
cases-exp-indent=2 (profile janestreet (file .ocamlformat:2))
cases-matching-exp-indent=normal (profile janestreet (file .ocamlformat:2))
disambiguate-non-breaking-match=false (profile janestreet (file .ocamlformat:2))
doc-comments=before (profile janestreet (file .ocamlformat:2))
doc-comments-padding=1 (profile janestreet (file .ocamlformat:2))
doc-comments-tag-only=fit (profile janestreet (file .ocamlformat:2))
dock-collection-brackets=true (file .ocamlformat:20)
exp-grouping=parens (profile janestreet (file .ocamlformat:2))
extension-indent=2 (profile janestreet (file .ocamlformat:2))
field-space=loose (profile janestreet (file .ocamlformat:2))
function-indent=2 (profile janestreet (file .ocamlformat:2))
function-indent-nested=never (profile janestreet (file .ocamlformat:2))
if-then-else=keyword-first (profile janestreet (file .ocamlformat:2))
indent-after-in=0 (profile janestreet (file .ocamlformat:2))
indicate-multiline-delimiters=closing-on-separate-line (file .ocamlformat:11)
indicate-nested-or-patterns=unsafe-no (profile janestreet (file .ocamlformat:2))
infix-precedence=parens (profile janestreet (file .ocamlformat:2))
leading-nested-match-parens=false (file .ocamlformat:12)
let-and=sparse (profile janestreet (file .ocamlformat:2))
let-binding-indent=2 (profile janestreet (file .ocamlformat:2))
let-binding-spacing=double-semicolon (profile janestreet (file .ocamlformat:2))
let-module=sparse (profile janestreet (file .ocamlformat:2))
line-endings=lf (profile janestreet (file .ocamlformat:2))
margin=80 (file .ocamlformat:4)
match-indent=0 (profile janestreet (file .ocamlformat:2))
match-indent-nested=never (profile janestreet (file .ocamlformat:2))
max-indent=2 (profile janestreet (file .ocamlformat:2))
module-item-spacing=compact (profile janestreet (file .ocamlformat:2))
nested-match=wrap (profile janestreet (file .ocamlformat:2))
ocp-indent-compat=false (file .ocamlformat:13)
parens-ite=true (profile janestreet (file .ocamlformat:2))
parens-tuple=multi-line-only (profile janestreet (file .ocamlformat:2))
parens-tuple-patterns=multi-line-only (profile janestreet (file .ocamlformat:2))
parse-docstrings=true (profile janestreet (file .ocamlformat:2))
parse-toplevel-phrases=false (profile janestreet (file .ocamlformat:2))
sequence-blank-line=compact (profile janestreet (file .ocamlformat:2))
sequence-style=terminator (profile janestreet (file .ocamlformat:2))
single-case=compact (file .ocamlformat:14)
space-around-arrays=true (profile janestreet (file .ocamlformat:2))
space-around-lists=true (profile janestreet (file .ocamlformat:2))
space-around-records=true (profile janestreet (file .ocamlformat:2))
space-around-variants=true (profile janestreet (file .ocamlformat:2))
stritem-extension-indent=2 (profile janestreet (file .ocamlformat:2))
type-decl=compact (file .ocamlformat:15)
type-decl-indent=2 (profile janestreet (file .ocamlformat:2))
wrap-comments=true (file .ocamlformat:16)
wrap-fun-args=true (file .ocamlformat:17)
profile=janestreet (file .ocamlformat:2)
```

**Comment by gpetiot** [comment] 2023-09-13 16:25
The issue is that you are using the janestreet profile, this profile is tailored towards what Jane Street engineers want, and a lot of work has been made in this direction in ocamlformat.0.26.0. 

The changelog lists the following changes:
- JaneStreet profile: treat comments as doc-comments (https://github.com/ocaml-ppx/ocamlformat/pull/2261, https://github.com/ocaml-ppx/ocamlformat/pull/2344, https://github.com/ocaml-ppx/ocamlformat/pull/2354, https://github.com/ocaml-ppx/ocamlformat/pull/2365, https://github.com/ocaml-ppx/ocamlformat/pull/2392, @gpetiot, @Julow)

#2261 made the janestreet profile not wrap docstrings, as per Jane Street instructions.

**Comment by vphantom** [comment] 2023-09-13 18:16
Wait, I thought that profile selection meant pre-defining all settings, and then after choosing a profile, we then set those settings which aren't to our liking.

Am I to understand that there are in effect "hidden settings" only accessible via profile selection?

**Comment by gpetiot** [comment] 2023-09-13 20:41
> Wait, I thought that profile selection meant pre-defining all settings, and then after choosing a profile, we then set those settings which aren't to our liking.

That's correct (still sometimes you might hit some edge cases that were not anticipated).
However the behavior of the janestreet profile is not as stable as the default one because we are still working with Jane Street to get something that suits them better, meaning this profile might still change again in the next releases. One of these changes is that the `wrap-comments` option should not impact the formatting of the docstrings.

> Am I to understand that there are in effect "hidden settings" only accessible via profile selection?

There is indeed a hidden setting named `wrap_docstrings` that is not accessible to the user (isn't even listed by `--print-config`), making the docstrings not wrap for the janestreet profile, but that is a detail of the implementation. We can discuss with @Julow about making this option public, but that was not our initial intent.

**Comment by vphantom** [comment] 2023-09-13 21:12
Ah ha! That explains a lot, merci beaucoup! Then I will print out my configuration and replicate it with another profile (probably the diff-friendly one), which should fix it. I'll report back on the result.

**Comment by Julow** [comment] 2023-09-14 11:47
The internal `wrap_docstrings` option allows docstrings to exceed the margin. It's implied by `parse-docstrings`. I'm not sure we want to expose that.

**Comment by gpetiot** [comment] 2023-09-14 16:03
I'm closing this issue then, feel free to open another issue if you encounter problems with the default or diff-friendly profile.

**Closed by gpetiot** 2023-09-14 16:03 UTC
Labels: Kind/Bug :x:
