### ISSUE TITLE
Switch from ocaml-migrate-parsetree to ppxlib

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#305] opened 2018-08-10 22:00 UTC
Instead of depending directly on ocaml-migrate-parsetree, use [ppxlib](https://github.com/ocaml-ppx/ppxlib)'s `Ast`.

Not a high priority currently, but if/when we want to combine ocamlformat with another ppx rewriter, they will need to agree on the Ast version, which ppxlib supports.

**Comment by hhugo** [comment] 2019-06-02 04:53
@jberdine, what would be a use-case for combining ocamlformat and another ppx ?

**Comment by emillon** [comment] 2020-09-10 08:55
Duplicate of #1460

**Comment by hhugo** [comment] 2021-05-20 12:48
Should this be closed ?

**Closed** 2021-05-20 13:28 UTC
