### ISSUE TITLE
How to handle versioning?

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#699] opened 2019-03-21 15:09 UTC
Hello,

I am happily using ocamlformat in several projects now, and it is getting more and more pleasant to use, so thanks for that.

However, I'm not sure how to handle different versions: if different developers have a different version, it might format differently. Setting `version` in `.ocamlformat` is useful, but since it is supported in a single opam version, it is difficult to work in several repos that use different versions. In addition, it makes setting ocamlformat in CI tricky, because it adds tight test-dependencies for different packages. 

I think that the problem is similar in `dune` (we don't want the semantics of dune files to change when upgrading dune, but that it's possible when manually upgrading the language version in `dune-project`).

Here is how a similar solution could work with `ocamlformat`:
- the notion of "language version" and "package version" become different
- all top-level `.ocamlformat` files have a `version` set. it corresponds to the language version used to format the source code
- a given ocamlformat binary can handle several language versions. the one it uses is set in project configuration files.
- in terms of opam constraints, a project that uses version X requires at least ocamlformat version Y
- old language versions can be dropped from time to time. this will translate to a higher bound on the ocamlformat dependency.

There is of course many choices to make, such as how to map language versions to opam versions (in dune, language 1.3 means dune >= 1.3.0 for example - it also means that we can make new versions that do not correspond to a language version); how to deprecate features (in dune this is tied to major releases, though we haven't made one yet), etc.

This versioning strategy can also be found in [debhelper](https://manpages.debian.org/testing/debhelper/debhelper.7.en.html#COMPATIBILITY_LEVELS).

The main drawback of this approach is that it requires wrapping every change behind a version check. In practice, with some combinators it's not too painful.

Let me know what you think. Thanks!

**Comment by jberdine** [comment] 2019-03-23 16:46
I am very very hesitant to adopt an approach, at this point, that would involve branching on versions in the formatting code. There are already too many such branches making the code complicated due to options.

Note that currently the version checking in the config file is actually too lenient. To get reproducible results, it is also required that the version of ocaml used to compile ocamlformat is the same, and perhaps also that of ocaml-migrate-parsetree. This is due to corner cases where the mapping done by ocaml-migrate-parsetree for different compiler versions can lead to slightly different comment placement. More commonly, the parser in different versions does not always give the same source locations, which also affects comment placement. Note that for this sort of version dependency, there isn't a feasible way to test in the formatter code and adjust behavior, it's too late.

I am not sure that the long-term solution for a versioned ocamlformat involves building ocamlformat in the opam switch used for the code being formatted. It seems more maintainable to build the versions of ocamlformat needed in separate switches, each with the needed compiler version. Then a small script could read the version field of the config file and dispatch to the appropriate ocamlformat binary.

**Comment by avsm** [comment] 2019-04-09 09:19
In order to make these host binaries, they will need distinct names then.  Perhaps one approach is to build stable versions of ocamlformat (e.g. the 1.0 release) as `ocamlformat-1.0` so that it can be invoked specifically by an editor.  That would also make coinstallation of the binaries significantly easier if multiple versions are required.

**Comment by gpetiot** [comment] 2019-04-16 04:26
Is this: https://github.com/ocaml/opam-repository/pull/13975 what you had in mind?

**Comment by gpetiot** [comment] 2021-09-30 14:32
The target (compiler) version is taken care of with the option `--ocaml-version` (#1759), some syntax changes are not handled yet (see https://github.com/ocaml-ppx/ocamlformat/issues/633#issuecomment-892547377 for a full list) but we're working on it.
I'm closing this one.

**Closed by gpetiot** 2021-09-30 14:32 UTC
Labels: Kind/To-discuss
