### ISSUE TITLE
Bug: ocamldoc lists are still being concatenated into one line in the presence of wrap-comments

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#968] opened 2019-08-14 18:30 UTC
I appear to still be seeing the behaviour from #477, when passing `--wrap-comments`.

 - `ocamlformat --version`: **0.11.0**

#### Input:

```ocaml
val flag : string -> t -> flag_payload option
(** [flag fl stmt] finds the flag by the name of [fl], {{!reso} resolves} it if
    necessary, and produces the payload there of, if any.

    This can yield ...

    - [None], indicating flag [fl] was not present at all.
    - [Some Empty], indicating flag [fl] was present, but resolved to having no payload.
    - [Some (Payload str)], indicating flag [fl] was present and became resolved to the payload [str]. This can involve resolution of the word immediately following [fl]. *)
```

#### Output:

```ocaml
val flag : string -> t -> flag_payload option
(** [flag fl stmt] finds the flag by the name of [fl], {{!reso} resolves} it if
    necessary, and produces the payload there of, if any.

    This can yield ...

    - [None], indicating flag [fl] was not present at all. - [Some Empty], indicating
      flag [fl] was present, but resolved to having no payload. - [Some (Payload str)],
      indicating flag [fl] was present and became resolved to the payload [str]. This can
      involve resolution of the word immediately following [fl]. *)
```

This seems specific to the inclusion of `--wrap-comments`; without that flag, this doesn't occur.

**Comment by gpetiot** [comment] 2019-08-15 06:17
Are you sure you pass the `parse-docstrings` option? I didn't manage to reproduce this bug.

**Comment by gpetiot** [comment] 2019-08-20 09:55
Closing this one because I can't reproduce it on master, feel free to re-open if it happens again.

**Closed by gpetiot** 2019-08-20 09:55 UTC
Labels: Kind/Bug
