### ISSUE TITLE
Bug: empty line introduced while formatting

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#1796] opened 2021-09-09 08:24 UTC
Format the following file with default options (tested with `main` on Unix). The empty line before `in` is removed but a new empty line is inserted after `in`.
```ocaml
let _ =
  let collateralized_contracts_mtas =
    Cva_common.
      [
        (swap_1_c, { minimum_transfert_amount = 0. });
        (swap_2_c, { minimum_transfert_amount = 0. });
        (swap_3_c, { minimum_transfert_amount = 0. });
      ]
    
  in
  ()
```

**Comment by nojb** [comment] 2021-09-09 08:39
Do let me know if you manage to reproduce the issue...

**Comment by gpetiot** [comment] 2021-09-09 18:23
I managed to reproduce the issue, this PR https://github.com/ocaml-ppx/ocamlformat/pull/1798 should fix it, but don't hesitate to let me know if the bug persists.

**Comment by Julow** [comment] 2021-09-10 12:33
This is an intended behavior, I think. What formatting do you expect ?

This option is on by default, which "preserve" an empty line between elements of a sequence.
```
       --sequence-blank-line={preserve-one|compact}
           Blank line between expressions of a sequence. preserve will keep a
           blank line between two expressions of a sequence if the input
           contains at least one. compact will not keep any blank line
           between expressions of a sequence. The default value is
           preserve-one.
```
`let` expressions are handled by this option too (this should be explained better). The newline is moved from before to after the `in` because that's the only place ocamlformat wants to put an empty line.

**Comment by nojb** [comment] 2021-09-10 13:30
> This is an intended behavior, I think. What formatting do you expect ?
> 
> This option is on by default, which "preserve" an empty line between elements of a sequence.
> 
> ```
>        --sequence-blank-line={preserve-one|compact}
>            Blank line between expressions of a sequence. preserve will keep a
>            blank line between two expressions of a sequence if the input
>            contains at least one. compact will not keep any blank line
>            between expressions of a sequence. The default value is
>            preserve-one.
> ```

What does "sequence" mean here? I thought it referred to `e1; e2`, but I don't see any such in the example...

**Comment by Julow** [comment] 2021-09-10 13:37
It does refer to `e1; e2` but actually applies to code like:
```
  foo;

  bar;

  let x = y in

  baz
```
we should probably use a different word than "sequence".

**Comment by nojb** [comment] 2021-09-10 13:42
> we should probably use a different word than "sequence".

Sorry, I probably don't understand what `preserve-one` means... am I understanding well that `ocamlformat` is seeing the empty line *before* the `in` and deciding that it needs to introduce an empty line *after* it?

**Comment by Julow** [comment] 2021-09-10 14:15
The logic is, if there's one or more empty lines between two elements of what we call "sequence" (vaguely defined in my comment above), print a single empty line between these two elements. 

Because this applies to only between two elements of a "sequence" (which the `in` alone isn't part of) and also because ocamlformat enforces a certain style, that newline can only be inserted after the `in`.

It was decided that this empty line should not be removed: https://github.com/ocaml-ppx/ocamlformat/pull/1077

**Comment by nojb** [comment] 2021-09-10 14:38
OK, let's assume it is expected... how does it relate to #1798 by @gpetiot ?

**Comment by Julow** [comment] 2021-09-10 14:58
This PR is removing the feature of keeping the blank line that is before the `in`. I'm not in favor but I'd wait for other opinions.

**Comment by gpetiot** [comment] 2021-09-10 15:46
I didn't have this case:
```
  let x =
    y

  in z
```
in mind when I worked on the PR.
We can either:
- check whether `in` starts the line, if that's the case then preceding linebreaks would be preserved
- do not preserve linebreaks before `in` at all (merging this PR)
- do nothing, the simple solution is to remove the blank line before the `in` from the input (is there a reason why it's there?)

Personally I think that the "preserve" options are becoming more and more of a burden to ocamlformat's maintainance, that may have been kind hearted of us to say yes when people asked for that, but maybe this kind of option would not be relevant for ocamlformat 1.0?
This one is even worse as we do not exactly preserve the position of the linebreak, so I understand why it's surprising to users.

**Comment by nojb** [comment] 2021-09-10 15:53
> Personally I think that the "preserve" options are becoming more and more of a burden to ocamlformat's maintainance, that may have been kind hearted of us to say yes when people asked for that, but maybe this kind of option would not be relevant for ocamlformat 1.0?

My 2c: having these kind of "preserve" option seems to go *against* the general philosophy of `ocamlformat` which is to enforce a given style. By "preserving" the input style, these options seem to do the opposite :)

So indeed it seems to me it would be better to get rid of them (especially if they also complexify the code and increase maintenance).

**Comment by gpetiot** [comment] 2022-02-24 17:36
Since this behavior is expected I am closing this issue.
We can come up with a better behavior in the future but that is not a priority right now.

**Closed by gpetiot** 2022-02-24 17:36 UTC
Labels: Kind/Bug :x:
