### ISSUE TITLE
Preserve original escape sequences in strings

### ISSUE THREAD

**Issue by edwintorok** [ocaml-ppx/ocamlformat#10] opened 2017-10-20 22:42 UTC
`"\xff\xaa\x55"`  gets converted to `"\255\170U"`, and `"A\xffB"` to `"A\255B"`
There should be a configuration field to specify whether this conversion is desired, and I'd prefer if `ocamlformat` wouldn't change the choice of escape sequence when all bytes in the string use the same escape sequence.

OTOH if someone writes "\xff\170U" .... I wouldn't mind if ocamlformat chose one.

**Comment by jberdine** [comment] 2017-10-20 22:57
The current situation is indeed suboptimal. The problem is that the parser eagerly interprets the escape sequences, so that by the time the formatter gets the parsetree, they have already been expanded. IIUC, the situation will improve for comments in 4.06.

**Comment by edwintorok** [comment] 2017-10-20 23:12
Could the output be reformatted to hex if a project's configuration specifies it prefers hex?

**Comment by jberdine** [comment] 2017-10-20 23:18
Potentially, I think so. Currently String.escaped is called to ensure the generated strings parse back to the same string. Some other function satisfying that same spec could be used instead. See Fmt_ast.fmt_constant.

**Comment by vjeux** [comment] 2017-10-21 00:14
For prettier (a JavaScript formatter), I've played with many variants around string escaping and the solution that ended up working was to read the original source (I hope that you have the node location) and just convert ' to " and fix the escaping and remove useless `\`. All the attempts at finding a consistent way to print those unicode characters / emoji ended up people creating issues about them.

**Comment by jberdine** [comment] 2017-10-21 00:54
I've heard rumblings that keeping the original strings in the parsetree is coming soon, so up to now I've been holding out on going back to the original source. Mostly a matter of prioritization.

**Comment by mbarbin** [comment] 2018-04-17 18:09
@vjeux's solution seems great.  I did not notice this issue, opened another one and seems like the discussion there reached the same conclusion.  Closing the other issue. #147

**Comment by jberdine** [comment] 2018-04-17 20:14
A hybrid solution would be to add a string escape mode for reusing the bytes of the input, and applying it selectively using attributes as per #81.

**Closed** 2018-04-23 23:56 UTC
Labels: enhancement, help wanted

**Comment by hcarty** [comment] 2018-04-24 01:29
Thank you everyone involved!
