### ISSUE TITLE
Bug: Closing parenthesis when a comment is present

### ISSUE THREAD

**Issue by pascutto** [ocaml-ppx/ocamlformat#1228] opened 2020-02-10 13:26 UTC
**Describe the bug**
With the latest release, the parenthesis around an expression with a comment get closed on the same line the comment is closed, which makes both code and comment to appear on the same line, and sounds wrong to me.

This code (ocamlformat.0.12):
```ocaml
let () =
  if false then ()
  else (
    print_string "Hello ";
    print_endline "World!"
    (* This is a long multi line comment, and I would expect the closing
       parenthesis to be on a different line than this one *)
    )
```

now becomes (ocamlformat.0.13.0):
```ocaml
let () =
  if false then ()
  else (
    print_string "Hello ";
    print_endline "World!"
    (* This is a long multi line comment, and I would expect the closing
       parenthesis to be on a different line than this one *) )
```

(A real example [here](https://github.com/mirage/irmin/pull/938/files#diff-61cfcc5e671d0a7cb72a7d4a8ca1a9d5R106))

**How to Reproduce**
This works with the default profile.

**Comment by Julow** [comment] 2020-02-10 13:53
Regression from https://github.com/ocaml-ppx/ocamlformat/pull/1122.
I think this is not really a regression, the placement is consistent with expressions:
```ocaml
let () =
  if false then ()
  else (
    print_string "Hello ";
    print_endline "World!" )
```

Maybe what's wrong is putting parenthesis at the end of lines?
This style prevent copying, deleting, (un)commenting code line by line. Also, when several closing parentheses accumulate, some effort is needed to decide where to add code and any mistake will result in confusing errors.

We have some logic in OCamlformat that detects this (eg. a sequence in an if, a match in a match) and put a space before the closing parenthesis. (called disambiguation)
What if we try inserting a newline instead ? (as a new option, this can be tested on projects like Irmin or OCamlformat)

**Comment by jberdine** [comment] 2020-05-04 22:20
It isn't a bug to place a closing paren after a multi-line comment. Placing something other than "punctuation" after anything multi-line is likely a bug.

There is a much wider scoped discussion to be had about an overall style that places closing parens e.g. on their own line, and whether multiple closing parens are allowed on a single line, or whether they each have to get their own, and if they do, then do they have to appear in the same column as their matching open paren, etc.

I don't think anyone is opposed to having that discussion, but unless there is a plan for an overall style that takes a significantly different view on where to place parens, it will just lead to inconsistent styles where some parens are placed one way and others another way. It is also necessary, I think, to have a plan for how to implement it without increasing the complexity of the implementation significantly.

**Comment by jberdine** [comment] 2020-05-19 21:58
I'll close this as the particular behavior in the OP is not a bug. A separate issue can be opened to discuss the wider question of closing paren placement if someone wants to work on it.

**Closed by jberdine** 2020-05-19 21:58 UTC
Labels: Kind/Bug :x:
