### ISSUE TITLE
trailing space at type ascription

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#640] opened 2019-02-28 02:14 UTC
```
$ cat .ocamlformat 
module-item-spacing=compact
doc-comments=before
ocp-indent-compat=true
break-sequences=true
type-decl=sparse
let-and=sparse
field-space=loose
extension-sugar=always
max-iters=3
quiet=true
cases-exp-indent=4
leading-nested-match-parens=true
```
```
$ opam config exec -- ocamlformat --version
0.8
```
So it formatting like
```
module Make (R : sig
    val function_name 
      :  prefix:string
      -> length:int
(* . . . *)
```
All fine, but extra ` `(a space) after *function_name*.

P.S.: Additional question: the `cases-exp-indent=4` indent not only match cases, but fun's part after `->`, so I forced to use ocp-indent to re-indent it back a little with config:
```
$ cat .ocp-indent 
max_indent=2
align_ops=false
align_params=always
match_clause=4
```

**Comment by gpetiot** [comment] 2019-02-28 03:22
The space issue has been fixed in #525 (next release should arrive soon).

As for cases-exp-indent I don't understand your issue, I get the same output with
`ocamlformat f.ml --cases-exp-indent 4` and `OCP_INDENT_CONFIG=match_clause=4,max_indent=2,align_ops=false,align_params=always ocp-indent f.ml` on this file for example:

```ocaml
let x = function
  | _ ->
      let k = y in
      let k = y in
      let u = p in
      let k = y in
      let u = p in
      let k = y in
      let u = p in
      let u = p in
      x + o
```

**Comment by Pitometsu** [comment] 2019-02-28 04:06
Oh, really, the last one can't reproduce: *ocamlformat* just put the `|` in case of `function _pattern_ ->`.
But LGFM. Thank you for clarification.

**Comment by Pitometsu** [comment] 2019-03-19 19:37
Oh, here what I mean:
```
  let bus : (module MSG_QUEUE) list =
    List.map comps ~f:(fun (module Comp : COMPONENT) ->
        (module CompWithQueue (Comp) : MSG_QUEUE) )
```
Instead of
```
  let bus : (module MSG_QUEUE) list =
    List.map comps ~f:(fun (module Comp : COMPONENT) ->
      (module CompWithQueue (Comp) : MSG_QUEUE) )
```

**Comment by jberdine** [comment] 2019-04-01 23:18
The indentation in the last comment is as intended. Otherwise if there are more args either of ~f:fun or applied to List.map, the indentation of the body would have to change.

**Closed by jberdine** 2019-04-01 23:18 UTC
