### ISSUE TITLE
Bug: ocamlformat fails with Bigarray extended indexing in OCaml 4.10.0

### ISSUE THREAD

**Issue by tachukao** [ocaml-ppx/ocamlformat#1273] opened 2020-03-05 16:38 UTC
ocamlformat fails to format code that uses latest Bigarray extended indexing feature in OCaml 4.10.0

Here is a simple script that breaks when I try and run ocamlformat on it

```ocaml
open Bigarray
let ( .%{ ;.. } ) = Genarray.get
let ( .%{ ;.. } <- ) = Genarray.set
let () = 
   let x = Genarray.create Float64 c_layout [|3;4;5|] in
   x.%{0;0;0} <- 3.;
   Printf.printf "%f\n" x.%{0;0;0} 
```

**Comment by emillon** [comment] 2020-03-06 13:00
Duplicate of #1218

**Comment by emillon** [comment] 2020-03-06 13:00
Indeed, ocamlformat does not support this at the moment.

**Closed** 2020-03-09 14:07 UTC
Labels: Kind/Bug :x:
