### ISSUE TITLE
Bug: Installing through esy on Windows due to `Unbound module In_channel`

### ISSUE THREAD

**Issue by Faholan** [ocaml-ppx/ocamlformat#1933] opened 2021-11-28 19:37 UTC
**Describe the bug**
When trying to install on Windows 10 through esy with ocaml 4.10.2 fails due to an `Unbound module In_channel`

**Detailed output**
```
C:\Users\Waylander\Documents\Coding\Option-info>esy
info esy 0.6.12 (using package.json)
info building @opam/ocamlformat@opam:0.19.0@d7e55490
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/ocamlformat@opam:0.19.0
    # esy-build-package: pwd: C:\Users\Waylander\.esy\3\b\opam__s__ocamlformat-opam__c__0.19.0-f78f7c76
    # esy-build-package: running: "dune" "build" "-p" "ocamlformat" "-j" "4" "@install"
          menhir vendor/ocaml-4.13/parser.{ml,mli}
    Grammar has 206 nonterminal symbols, among which 13 start symbols.
    Grammar has 123 terminal symbols.
    Grammar has 847 productions.
    Built an LR(0) automaton with 1845 states.
    The grammar is not SLR(1) -- 137 states have a conflict.
    The construction mode is lalr.
    Built an LR(1) automaton with 1845 states.
    1062 shift/reduce conflicts were silently solved.
        ocamlopt lib/.ocamlformat_lib.objs/native/ocamlformat_lib__Conf.{cmx,o} (exit 2)
    (cd _build/default && C:\Users\Waylander\.esy\3____________________________________________________________\i\ocaml-4.10.2000-64d8b100\bin\ocamlopt.opt.exe -w -40 -noassert -open Ocaml_413 -open Ocamlformat_stdlib -g -I lib/.ocamlformat_lib.objs/byte -I lib/.ocamlformat_lib.objs/native -I C:/Users/Waylander/.esy/3____________________________________________________________/i/ocaml-4.10.2000-64d8b100/lib/ocaml\compiler-libs -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__astring-opam__c__0.8.5-72bed4c2/lib\astring -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__base-opam__c__v0.14.2-8211ef5a/lib\base -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__base-opam__c__v0.14.2-8211ef5a/lib\base\base_internalhash_types -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__base-opam__c__v0.14.2-8211ef5a/lib\base\caml -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__base-opam__c__v0.14.2-8211ef5a/lib\base\shadow_stdlib -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__cmdliner-opam__c__1.0.4-be4ea5c8/lib\cmdliner -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__dune_build_info-opam__c__2.9.1-c5c711dd/lib\dune-build-info -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__fpath-opam__c__0.7.3-690d2632/lib\fpath -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__menhirlib-opam__c__20211012-fc792a46/lib\menhirLib -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__ocamlfind-opam__c__1.9.1-092bb39b/lib\bytes -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__ocp_indent-opam__c__1.7.0-954ddf72/lib\ocp-indent\lexer -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__ocp_indent-opam__c__1.7.0-954ddf72/lib\ocp-indent\lib -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__ocp_indent-opam__c__1.7.0-954ddf72/lib\ocp-indent\utils -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__odoc_parser-opam__c__0.9.0-99e9bb40/lib\odoc-parser -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__re-opam__c__1.10.3-f970ddd3/lib\re -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__result-opam__c__1.5-f793447d/lib\result -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__seq-opam__c__base-248ea357/lib\seq -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__sexplib0-opam__c__v0.14.0-c1829eb5/lib\sexplib0 -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__stdio-opam__c__v0.14.0-c260cab6/lib\stdio -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__uchar-opam__c__0.0.2-bb6d454a/lib\uchar -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__uucp-opam__c__14.0.0-bb03e223/lib\uucp -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__uuseg-opam__c__14.0.0-ef61801d/lib\uuseg -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__uuseg-opam__c__14.0.0-ef61801d/lib\uuseg\string -I C:/Users/Waylander/.esy/3____________________________________________________________/i/opam__s__uutf-opam__c__1.0.2-1126abc8/lib\uutf -I vendor/ocaml-4.13/.ocaml_413.objs/byte -I vendor/ocaml-4.13/.ocaml_413.objs/native -I vendor/ocamlformat-stdlib/.ocamlformat_stdlib.objs/byte -I vendor/ocamlformat-stdlib/.ocamlformat_stdlib.objs/native -I vendor/ocamlformat_support/.format_.objs/byte -I vendor/ocamlformat_support/.format_.objs/native -I vendor/parse-wyc/lib/.parse_wyc.objs/byte -I vendor/parse-wyc/lib/.parse_wyc.objs/native -I vendor/parser-shims/.parser_shims.objs/byte -I vendor/parser-shims/.parser_shims.objs/native -intf-suffix .ml -no-alias-deps -open Ocamlformat_lib -o lib/.ocamlformat_lib.objs/native/ocamlformat_lib__Conf.cmx -c -impl lib/Conf.ml)
    File "lib/Conf.ml", line 1906, characters 6-26:
    1906 |       In_channel.with_file (Fpath.to_string filename) ~f:(fun ic ->
                 ^^^^^^^^^^^^^^^^^^^^
    Error: Unbound module In_channel
    error: command failed: "dune" "build" "-p" "ocamlformat" "-j" "4" "@install" (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/ocamlformat@opam:0.19.0
esy: exiting due to errors above
```

What should I do in order to get this dependency ?

**Comment by gpetiot** [comment] 2021-11-28 20:03
I'm not sure anyone tried to install ocamlformat with esy until now, the preferred way to install it is with `opam` (`opam install ocamlformat`), the dependency you need is the `base` library (opam will fetch all dependencies)

**Comment by Faholan** [comment] 2021-11-28 21:23
The main issue is that I'm under Windows, so I had to use esy in order to install ocaml.
Also, adding the `@opam/base` dependency didn't solve the issue, the build is still failing with the exact same error message

**Comment by gpetiot** [comment] 2021-11-29 08:41
I see, here is another way that could work for windows then: https://diskuv.gitlab.io/diskuv-ocaml/index.html apparently this distribution already includes opam and ocamlformat

**Comment by jberdine** [comment] 2021-11-29 10:45
The `In_channel` module is from the `stdio` package, do you have that installed?

**Comment by gpetiot** [comment] 2021-12-03 12:21
I encourage you to open an issue on https://github.com/esy/esy if necessary, since this issue is not caused by ocamlformat I'm closing it.

**Closed by gpetiot** 2021-12-03 12:21 UTC
Labels: Kind/Bug :x:
