### ISSUE TITLE
Bug: does not stabilize with infix operator and double comment

### ISSUE THREAD

**Issue by paracetamolo** [ocaml-ppx/ocamlformat#2072] opened 2022-05-08 20:27 UTC
With the expression `1 + (* *) (* *) 1` ocamlformat outputs `  BUG: formatting did not stabilize after 10 iterations.`

`.ocamlformat`:
```
version=e9ac525
profile=default
```

**Comment by gpetiot** [comment] 2022-05-09 12:18
Hi, I will have a look, but this is a duplicate of issue #2063 so I am closing this one, keep an eye on the other one for updates.

**Closed by gpetiot** 2022-05-09 12:18 UTC
Labels: Kind/Bug :x:
