### ISSUE TITLE
Bug: extra line with whitespace at the end of the file

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#1789] opened 2021-09-03 13:34 UTC
**Describe the bug**

Version 0.19 is adding an extra line with some whitespace at the end of the file. I didn't have the issue with 0.15.

**How to Reproduce**

take this file and reformat it 

```ocaml
let config =
  Route_config.
    {
      kind = TmpWebPublicBoth;
      sensitivity = Sensitivity.Not_sensitive;
      allowed_methods = POST_only;
      (* target is not used for this web endpoint, check routes in endpoint wppToken.ml file *)
      target = (fun () -> Routes.empty);}
```

it gives this result, with a line that contain two spaces

```ocaml
let config =
  Route_config.
    {
      kind = TmpWebPublicBoth;
      sensitivity = Sensitivity.Not_sensitive;
      allowed_methods = POST_only;
      (* target is not used for this web endpoint, check routes in endpoint wppToken.ml file *)
      target = (fun () -> Routes.empty);
    }
  
```

```
profile=default
quiet=false
max-iters=10
comment-check=true
wrap-fun-args=true (file ../../../../.ocamlformat:31)
wrap-comments=false
type-decl-indent=2
type-decl=sparse (file ../../../../.ocamlformat:30)
stritem-extension-indent=0
space-around-variants=true (file ../../../../.ocamlformat:29)
space-around-records=true (file ../../../../.ocamlformat:28)
space-around-lists=true (file ../../../../.ocamlformat:27)
space-around-arrays=true (file ../../../../.ocamlformat:26)
single-case=compact
sequence-style=terminator (file ../../../../.ocamlformat:25)
sequence-blank-line=preserve-one (file ../../../../.ocamlformat:24)
parse-docstrings=false
parens-tuple-patterns=multi-line-only
parens-tuple=multi-line-only (file ../../../../.ocamlformat:23)
parens-ite=true (file ../../../../.ocamlformat:22)
ocp-indent-compat=true (file ../../../../.ocamlformat:21)
nested-match=align (file ../../../../.ocamlformat:20)
module-item-spacing=sparse
max-indent=2 (file ../../../../.ocamlformat:19)
match-indent-nested=never
match-indent=0
margin=120 (file ../../../.ocamlformat:1)
line-endings=lf
let-module=compact
let-binding-spacing=compact
let-binding-indent=2
let-and=sparse (file ../../../../.ocamlformat:17)
leading-nested-match-parens=true (file ../../../../.ocamlformat:16)
infix-precedence=indent
indicate-nested-or-patterns=unsafe-no (file ../../../../.ocamlformat:15)
indicate-multiline-delimiters=closing-on-separate-line (file ../../../../.ocamlformat:14)
indent-after-in=0
if-then-else=compact
function-indent-nested=never
function-indent=2
field-space=loose (file ../../../../.ocamlformat:13)
extension-indent=2
exp-grouping=preserve (file ../../../../.ocamlformat:12)
dock-collection-brackets=true (file ../../../../.ocamlformat:7)
doc-comments-tag-only=default
doc-comments-padding=2
doc-comments=before (file ../../../../.ocamlformat:11)
disambiguate-non-breaking-match=false
disable=false
cases-matching-exp-indent=normal
cases-exp-indent=2 (file ../../../../.ocamlformat:10)
break-struct=natural (file ../../../../.ocamlformat:9)
break-string-literals=auto
break-sequences=true (file ../../../../.ocamlformat:8)
break-separators=after (file ../../../../.ocamlformat:5)
break-infix-before-func=false (file ../../../../.ocamlformat:3)
break-infix=fit-or-vertical (file ../../../../.ocamlformat:4)
break-fun-sig=wrap
break-fun-decl=wrap
break-collection-expressions=fit-or-vertical
break-cases=toplevel (file ../../../../.ocamlformat:2)
break-before-in=fit-or-vertical
assignment-operator=end-line
align-variants-decl=false
align-constructors-decl=false
align-cases=false
```

**Comment by gpetiot** [comment] 2021-09-03 14:41
This should be fixed by #1786

**Closed** 2021-09-09 06:57 UTC
Labels: Kind/Bug :x:

**Comment by Khady** [comment] 2021-09-09 14:50
It seems to be, thanks

**Comment by Khady** [comment] 2021-09-30 16:07
Is there a chance to get a minor release with the fix for this issue? It's a bit more annoying than some other issues because ocamlformat and the common "remove trailing whitespace" config from editors are fighting. If "remove trailing whitespace" happens after ocamlformat I end up being forced to do the formatting from the cli to have the correct result.

**Comment by gpetiot** [comment] 2021-09-30 22:00
I planned to cut a release before/around mid-october since we already have quite a few bugfixes since the last one. This can be done after I checked the new release does not introduce any regressions for our users.
